# Generated by Django 3.1.4 on 2020-12-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("disciplines", "0001_initial"),
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentcurriculum", unique_together={("discipline", "student")},
        ),
    ]
