# Generated by Django 3.1.4 on 2020-12-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_auto_20201206_2221"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcurriculum",
            name="course",
            field=models.CharField(
                default=1, max_length=90, verbose_name="course name"
            ),
            preserve_default=False,
        ),
    ]
