# Generated by Django 3.1.4 on 2020-12-07 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disciplines", "0001_initial"),
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="itemlist", name="created_at",),
        migrations.AddField(
            model_name="itemlist",
            name="discipline",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="disciplines.discipline",
            ),
            preserve_default=False,
        ),
    ]
