# Generated by Django 3.1.4 on 2020-12-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["name"], name="students_st_name_0bae46_idx"),
        ),
    ]
