# Generated by Django 3.1.4 on 2020-12-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disciplines", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="discipline",
            index=models.Index(fields=["name"], name="disciplines_name_756e25_idx"),
        ),
    ]
